// Package fieldgen generates typed policy field descriptors from Go argument
// structs. For each type it emits a *Fields descriptor whose leaves are
// policy.Selector[T] values carrying a jq selector path, so policies can be
// authored against real fields with compile-time type checking. It is a
// sidecar to cbor-gen: point it at the same argument types and it derives the
// selector paths from their cborgen tags.
//
// Descriptor *types* are path-free (a leaf is policy.Selector[T]); the
// generated *values* bake in the paths. The same descriptor type therefore
// serves both nested access (absolute path, e.g. ".blob.digest") and slice/map
// elements (element-relative path, e.g. ".digest"), the latter handed to the
// closure of policy.Each / policy.Some.
package fieldgen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"strings"
)

const policyPkg = "github.com/fil-forge/ucantone/ucan/delegation/policy"

// Options configures descriptor generation.
type Options struct {
	// Opaque lists types to treat as leaf selectors even though they are
	// structs with exported fields — i.e. do not recurse into them. Use this
	// for types whose on-the-wire shape is produced by a hand-written CBOR
	// marshaler that does not match their Go struct (e.g. promise.AwaitOK,
	// which marshals as {"await/ok": cid} regardless of its Go fields). Each
	// entry is a zero value of the type (e.g. promise.AwaitOK{}).
	Opaque []any
}

// WriteFieldDescriptors generates policy field descriptors for the given types
// and writes them, gofmt'd, to outPath in package pkgName. Each argument should
// be a zero value of a struct type (e.g. types.RetrieveArguments{}).
func WriteFieldDescriptors(outPath, pkgName string, types ...any) error {
	return WriteFieldDescriptorsWithOptions(outPath, pkgName, Options{}, types...)
}

// WriteFieldDescriptorsWithOptions is [WriteFieldDescriptors] with extra
// configuration; see [Options].
func WriteFieldDescriptorsWithOptions(outPath, pkgName string, opts Options, types ...any) error {
	g := &gen{
		pkgName:   pkgName,
		imports:   map[string]string{policyPkg: "policy"},
		descNames: map[reflect.Type]string{},
		opaque:    map[reflect.Type]bool{},
	}
	for _, o := range opts.Opaque {
		if ot := reflect.TypeOf(o); ot != nil {
			g.opaque[deref(ot)] = true
		}
	}
	for _, t := range types {
		rt := reflect.TypeOf(t)
		if rt == nil || rt.Kind() != reflect.Struct {
			return fmt.Errorf("WriteFieldDescriptors: %T is not a struct", t)
		}
		if g.selfPkg == "" {
			g.selfPkg = rt.PkgPath()
		}
		g.collect(rt)
		g.roots = append(g.roots, rt)
	}
	src, err := g.render()
	if err != nil {
		return err
	}
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w\n%s", err, src)
	}
	return os.WriteFile(outPath, formatted, 0o644)
}

type gen struct {
	pkgName   string
	selfPkg   string                // import path of the target package (rendered unqualified)
	imports   map[string]string     // pkgpath -> alias
	descNames map[reflect.Type]string
	opaque    map[reflect.Type]bool // types to treat as leaves (no recursion)
	order     []reflect.Type        // struct types needing a descriptor, in discovery order
	roots     []reflect.Type
}

// collect walks t, assigning a descriptor name to every navigable struct type
// reachable through fields, slice elements, and map values.
func (g *gen) collect(t reflect.Type) {
	if _, done := g.descNames[t]; done {
		return
	}
	if t.Name() == "" {
		return // anonymous struct, unsupported
	}
	g.descNames[t] = t.Name() + "Fields"
	g.order = append(g.order, t)
	for i := range t.NumField() {
		sf := t.Field(i)
		if !sf.IsExported() || ipldKey(sf) == "-" {
			continue
		}
		if et := g.navigableElem(sf.Type); et != nil {
			g.collect(et)
		}
	}
}

func (g *gen) render() ([]byte, error) {
	var body bytes.Buffer

	// Descriptor type declarations.
	for _, t := range g.order {
		fmt.Fprintf(&body, "// %s is the policy field descriptor type for %s.\n", g.descNames[t], t.Name())
		fmt.Fprintf(&body, "type %s struct {\n", g.descNames[t])
		for i := range t.NumField() {
			sf := t.Field(i)
			if !sf.IsExported() || ipldKey(sf) == "-" {
				continue
			}
			fmt.Fprintf(&body, "\t%s %s\n", sf.Name, g.descFieldType(sf.Type))
		}
		body.WriteString("}\n\n")
	}

	// Root descriptor values. The entry-point var is named after the source
	// type; its descriptor type is <name>Fields (used as the Each/Some closure
	// parameter type), so the two never collide.
	for _, t := range g.roots {
		fmt.Fprintf(&body, "// %s is the policy field descriptor for %s.\n", t.Name(), t.Name())
		fmt.Fprintf(&body, "var %s = %s\n\n", t.Name(), g.descValue(t, ""))
	}

	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by fieldgen; DO NOT EDIT.\n\npackage %s\n\n", g.pkgName)
	if len(g.imports) > 0 {
		out.WriteString("import (\n")
		paths := make([]string, 0, len(g.imports))
		for p := range g.imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			fmt.Fprintf(&out, "\t%s %q\n", g.imports[p], p)
		}
		out.WriteString(")\n\n")
	}
	out.Write(body.Bytes())
	return out.Bytes(), nil
}

// descFieldType renders the descriptor struct field type for a source field.
func (g *gen) descFieldType(ft reflect.Type) string {
	pol := g.pkgAlias(policyPkg)
	switch {
	case g.isLeaf(ft):
		return fmt.Sprintf("%s.Selector[%s]", pol, g.qual(ft))
	case g.navStruct(ft) != nil: // (possibly pointer to) navigable struct
		return g.descNames[g.navStruct(ft)]
	case ft.Kind() == reflect.Slice:
		return fmt.Sprintf("%s.SliceSelector[%s]", pol, g.elemDescType(ft.Elem()))
	case ft.Kind() == reflect.Map:
		return fmt.Sprintf("%s.MapSelector[%s]", pol, g.elemDescType(ft.Elem()))
	default:
		// Fallback: treat as an opaque leaf.
		return fmt.Sprintf("%s.Selector[%s]", pol, g.qual(ft))
	}
}

// elemDescType is the descriptor type of a slice/map element.
func (g *gen) elemDescType(et reflect.Type) string {
	if ns := g.navStruct(et); ns != nil {
		return g.descNames[ns]
	}
	return fmt.Sprintf("%s.Selector[%s]", g.pkgAlias(policyPkg), g.qual(et))
}

// descValue renders the composite literal initializing the descriptor for t,
// with selector paths prefixed by prefix (root: "").
func (g *gen) descValue(t reflect.Type, prefix string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s{\n", g.descNames[t])
	for i := range t.NumField() {
		sf := t.Field(i)
		if !sf.IsExported() || ipldKey(sf) == "-" {
			continue
		}
		path := prefix + "." + ipldKey(sf)
		fmt.Fprintf(&b, "\t%s: %s,\n", sf.Name, g.fieldValue(sf.Type, path))
	}
	b.WriteString("}")
	return b.String()
}

func (g *gen) fieldValue(ft reflect.Type, path string) string {
	pol := g.pkgAlias(policyPkg)
	switch {
	case g.isLeaf(ft):
		return fmt.Sprintf("%s.NewSelector[%s](%q)", pol, g.qual(ft), path)
	case g.navStruct(ft) != nil: // a (pointer to) navigable struct occupies the same path
		return g.descValue(g.navStruct(ft), path)
	case ft.Kind() == reflect.Slice:
		return fmt.Sprintf("%s.NewSliceSelector[%s](%q, %s)", pol, g.elemDescType(ft.Elem()), path, g.elemValue(ft.Elem()))
	case ft.Kind() == reflect.Map:
		return fmt.Sprintf("%s.NewMapSelector[%s](%q, %s)", pol, g.elemDescType(ft.Elem()), path, g.elemValue(ft.Elem()))
	default:
		return fmt.Sprintf("%s.NewSelector[%s](%q)", pol, g.qual(ft), path)
	}
}

// elemValue renders the element descriptor of a slice/map: a struct descriptor
// with element-relative paths, or an identity selector for scalar elements.
func (g *gen) elemValue(et reflect.Type) string {
	if ns := g.navStruct(et); ns != nil {
		return g.descValue(ns, "")
	}
	return fmt.Sprintf("%s.NewSelector[%s](%q)", g.pkgAlias(policyPkg), g.qual(et), ".")
}

// qual renders a Go type as source, recording any package import, e.g.
// "multihash.Multihash", "*big.Int", "[]byte", "uint64". Named types (including
// named slices like multihash.Multihash) are kept whole; only unnamed composite
// types are decomposed.
func (g *gen) qual(t reflect.Type) string {
	if t.Name() != "" && t.PkgPath() != "" {
		if t.PkgPath() == g.selfPkg {
			return t.Name()
		}
		// reflect's String() qualifies with the real package name (e.g.
		// "multihash.Multihash" for package multihash at .../go-multihash),
		// which the path's last segment does not always match.
		s := t.String()
		pkgName, _, _ := strings.Cut(s, ".")
		g.imports[t.PkgPath()] = pkgName
		return s
	}
	switch t.Kind() {
	case reflect.Pointer:
		return "*" + g.qual(t.Elem())
	case reflect.Slice:
		return "[]" + g.qual(t.Elem())
	case reflect.Array:
		return fmt.Sprintf("[%d]%s", t.Len(), g.qual(t.Elem()))
	case reflect.Map:
		return fmt.Sprintf("map[%s]%s", g.qual(t.Key()), g.qual(t.Elem()))
	}
	return t.String() // builtin (uint64, string, ...)
}

// pkgAlias returns the import alias for an already-registered package path
// (the policy package, registered at construction).
func (g *gen) pkgAlias(path string) string {
	return g.imports[path]
}

// isLeaf reports whether t is treated as a scalar policy value rather than a
// navigable map. Scalars and byte slices are leaves; structs with no exported
// fields (cid.Cid, did.DID, big.Int) are opaque leaves; structs with exported
// fields are navigable.
func isLeaf(t reflect.Type) bool {
	switch t.Kind() {
	case reflect.Bool, reflect.String,
		reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr,
		reflect.Float32, reflect.Float64:
		return true
	case reflect.Slice, reflect.Array:
		return t.Elem().Kind() == reflect.Uint8 // []byte / multihash.Multihash
	case reflect.Pointer:
		return isLeaf(t.Elem())
	case reflect.Struct:
		return !hasExportedField(t)
	}
	return false
}

// deref strips a single pointer, e.g. *Blob -> Blob.
func deref(t reflect.Type) reflect.Type {
	if t.Kind() == reflect.Pointer {
		return t.Elem()
	}
	return t
}

// isLeaf reports whether t is a leaf for this generation, consulting the
// opaque set in addition to the structural rule (see the package [isLeaf]).
func (g *gen) isLeaf(t reflect.Type) bool {
	return g.opaque[deref(t)] || isLeaf(t)
}

// navStruct returns the navigable struct type t denotes, dereferencing a
// single pointer (e.g. *Blob -> Blob), or nil if t is a leaf (structurally or
// because it was declared opaque) or not a struct.
func (g *gen) navStruct(t reflect.Type) reflect.Type {
	if g.opaque[deref(t)] {
		return nil
	}
	return navStruct(t)
}

// navigableElem returns the navigable struct type reachable through field type
// ft (the field itself, or a slice/map element), or nil if ft bottoms out in a
// leaf. Used to discover descriptor types to generate.
func (g *gen) navigableElem(ft reflect.Type) reflect.Type {
	if ns := g.navStruct(ft); ns != nil {
		return ns
	}
	switch ft.Kind() {
	case reflect.Slice, reflect.Array, reflect.Map:
		return g.navStruct(ft.Elem())
	}
	return nil
}

// navStruct returns the navigable struct type t denotes, dereferencing a
// single pointer (e.g. *Blob -> Blob), or nil if t is a leaf or not a struct.
// A struct with no exported fields (cid.Cid, did.DID, big.Int) is a leaf.
func navStruct(t reflect.Type) reflect.Type {
	if t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t.Kind() == reflect.Struct && !isLeaf(t) {
		return t
	}
	return nil
}

func hasExportedField(t reflect.Type) bool {
	for i := range t.NumField() {
		if t.Field(i).IsExported() {
			return true
		}
	}
	return false
}

// ipldKey returns the IPLD map key for a struct field: the cborgen tag name if
// present, otherwise the Go field name (cbor-gen's default).
func ipldKey(sf reflect.StructField) string {
	if tag, ok := sf.Tag.Lookup("cborgen"); ok {
		if name, _, _ := strings.Cut(tag, ","); name != "" {
			return name
		}
	}
	return sf.Name
}
