// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	did "github.com/fil-forge/ucantone/did"
	datamodel "github.com/fil-forge/ucantone/ipld/datamodel"
	ucan "github.com/fil-forge/ucantone/ucan"
	command "github.com/fil-forge/ucantone/ucan/command"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *TaskModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Args (datamodel.Raw) (struct)
	if len("args") > 8192 {
		return fmt.Errorf("String in field \"args\" was too long")
	}
	if err := jw.WriteString(string("args")); err != nil {
		return fmt.Errorf("\"args\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Args.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Args: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cmd (command.Command) (string)
	if len("cmd") > 8192 {
		return fmt.Errorf("String in field \"cmd\" was too long")
	}
	if err := jw.WriteString(string("cmd")); err != nil {
		return fmt.Errorf("\"cmd\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Cmd) > 8192 {
		return fmt.Errorf("String in field t.Cmd was too long")
	}
	if err := jw.WriteString(string(t.Cmd)); err != nil {
		return fmt.Errorf("t.Cmd: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Nonce ([]uint8) (slice)
	if len("nonce") > 8192 {
		return fmt.Errorf("String in field \"nonce\" was too long")
	}
	if err := jw.WriteString(string("nonce")); err != nil {
		return fmt.Errorf("\"nonce\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Nonce) > 2097152 {
		return fmt.Errorf("Byte array in field t.Nonce was too long")
	}

	if err := jw.WriteBytes(t.Nonce); err != nil {
		return fmt.Errorf("t.Nonce: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Sub (did.DID) (struct)
	if len("sub") > 8192 {
		return fmt.Errorf("String in field \"sub\" was too long")
	}
	if err := jw.WriteString(string("sub")); err != nil {
		return fmt.Errorf("\"sub\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Sub.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Sub: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *TaskModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = TaskModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("TaskModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("TaskModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("TaskModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("TaskModel: string too large")
				}
				return fmt.Errorf("TaskModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("TaskModel: %w", err)
			}
			switch name {

			// t.Args (datamodel.Raw) (struct)
			case "args":

				if err := t.Args.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Args: %w", err)
				}

				// t.Cmd (command.Command) (string)
			case "cmd":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Cmd: string too long")
						}
						return fmt.Errorf("t.Cmd: %w", err)
					}
					t.Cmd = command.Command(sval)
				}

				// t.Nonce ([]uint8) (slice)
			case "nonce":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Nonce: byte array too large")
						}
						return fmt.Errorf("t.Nonce: %w", err)
					}
					if len(bval) > 0 {
						t.Nonce = []uint8(bval)
					}
				}

				// t.Sub (did.DID) (struct)
			case "sub":

				if err := t.Sub.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Sub: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("TaskModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("TaskModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("TaskModel: map too large")
			}
		}
	}

	return nil
}
func (t *TokenPayloadModel1_0_0_rc1) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Args (datamodel.Raw) (struct)
	if len("args") > 8192 {
		return fmt.Errorf("String in field \"args\" was too long")
	}
	if err := jw.WriteString(string("args")); err != nil {
		return fmt.Errorf("\"args\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Args.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Args: %w", err)
	}
	written++
	if t.Aud != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Aud (did.DID) (struct)
	if t.Aud != nil {
		if len("aud") > 8192 {
			return fmt.Errorf("String in field \"aud\" was too long")
		}
		if err := jw.WriteString(string("aud")); err != nil {
			return fmt.Errorf("\"aud\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if err := t.Aud.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("t.Aud: %w", err)
		}
		written++
	}
	if t.Cause != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Cause (cid.Cid) (struct)
	if t.Cause != nil {
		if len("cause") > 8192 {
			return fmt.Errorf("String in field \"cause\" was too long")
		}
		if err := jw.WriteString(string("cause")); err != nil {
			return fmt.Errorf("\"cause\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}

		if t.Cause == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("t.Cause: %w", err)
			}
		} else {
			if err := jw.WriteCid(*t.Cause); err != nil {
				return fmt.Errorf("t.Cause: %w", err)
			}
		}

		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cmd (command.Command) (string)
	if len("cmd") > 8192 {
		return fmt.Errorf("String in field \"cmd\" was too long")
	}
	if err := jw.WriteString(string("cmd")); err != nil {
		return fmt.Errorf("\"cmd\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Cmd) > 8192 {
		return fmt.Errorf("String in field t.Cmd was too long")
	}
	if err := jw.WriteString(string(t.Cmd)); err != nil {
		return fmt.Errorf("t.Cmd: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Exp (ucan.UnixTimestamp) (int64)
	if len("exp") > 8192 {
		return fmt.Errorf("String in field \"exp\" was too long")
	}
	if err := jw.WriteString(string("exp")); err != nil {
		return fmt.Errorf("\"exp\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if t.Exp == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("t.Exp: %w", err)
		}
	} else {
		if err := jw.WriteInt64(int64(*t.Exp)); err != nil {
			return fmt.Errorf("t.Exp: %w", err)
		}
	}

	written++
	if t.Iat != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Iat (ucan.UnixTimestamp) (int64)
	if t.Iat != nil {
		if len("iat") > 8192 {
			return fmt.Errorf("String in field \"iat\" was too long")
		}
		if err := jw.WriteString(string("iat")); err != nil {
			return fmt.Errorf("\"iat\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}

		if t.Iat == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("t.Iat: %w", err)
			}
		} else {
			if err := jw.WriteInt64(int64(*t.Iat)); err != nil {
				return fmt.Errorf("t.Iat: %w", err)
			}
		}

		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Iss (did.DID) (struct)
	if len("iss") > 8192 {
		return fmt.Errorf("String in field \"iss\" was too long")
	}
	if err := jw.WriteString(string("iss")); err != nil {
		return fmt.Errorf("\"iss\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Iss.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Iss: %w", err)
	}
	written++
	if t.Meta != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Meta (datamodel.Raw) (struct)
	if t.Meta != nil {
		if len("meta") > 8192 {
			return fmt.Errorf("String in field \"meta\" was too long")
		}
		if err := jw.WriteString(string("meta")); err != nil {
			return fmt.Errorf("\"meta\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if err := t.Meta.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("t.Meta: %w", err)
		}
		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Nonce ([]uint8) (slice)
	if len("nonce") > 8192 {
		return fmt.Errorf("String in field \"nonce\" was too long")
	}
	if err := jw.WriteString(string("nonce")); err != nil {
		return fmt.Errorf("\"nonce\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Nonce) > 2097152 {
		return fmt.Errorf("Byte array in field t.Nonce was too long")
	}

	if err := jw.WriteBytes(t.Nonce); err != nil {
		return fmt.Errorf("t.Nonce: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Prf ([]cid.Cid) (slice)
	if len("prf") > 8192 {
		return fmt.Errorf("String in field \"prf\" was too long")
	}
	if err := jw.WriteString(string("prf")); err != nil {
		return fmt.Errorf("\"prf\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Prf) > 8192 {
		return fmt.Errorf("Slice value in field t.Prf was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Prf: %w", err)
	}
	for i, v := range t.Prf {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Prf: %w", err)
			}
		}

		if err := jw.WriteCid(v); err != nil {
			return fmt.Errorf("v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Prf: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Sub (did.DID) (struct)
	if len("sub") > 8192 {
		return fmt.Errorf("String in field \"sub\" was too long")
	}
	if err := jw.WriteString(string("sub")); err != nil {
		return fmt.Errorf("\"sub\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Sub.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Sub: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *TokenPayloadModel1_0_0_rc1) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = TokenPayloadModel1_0_0_rc1{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("TokenPayloadModel1_0_0_rc1: string too large")
				}
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
			}
			switch name {

			// t.Args (datamodel.Raw) (struct)
			case "args":

				if err := t.Args.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Args: %w", err)
				}

				// t.Aud (did.DID) (struct)
			case "aud":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("t.Aud: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("t.Aud: %w", err)
						}
					} else {
						t.Aud = new(did.DID)
						if err := t.Aud.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Aud pointer: %w", err)
						}
					}
				}

				// t.Cause (cid.Cid) (struct)
			case "cause":
				{

					c, err := jr.ReadCidOrNull()
					if err != nil {
						return fmt.Errorf("t.Cause: %w", err)
					}
					t.Cause = c

				}

				// t.Cmd (command.Command) (string)
			case "cmd":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Cmd: string too long")
						}
						return fmt.Errorf("t.Cmd: %w", err)
					}
					t.Cmd = command.Command(sval)
				}

				// t.Exp (ucan.UnixTimestamp) (int64)
			case "exp":
				{

					nval, err := jr.ReadNumberAsInt64OrNull()
					if err != nil {
						return fmt.Errorf("t.Exp: %w", err)
					}
					if nval != nil {
						typed := ucan.UnixTimestamp(*nval)
						t.Exp = &typed
					}

				}

				// t.Iat (ucan.UnixTimestamp) (int64)
			case "iat":
				{

					nval, err := jr.ReadNumberAsInt64OrNull()
					if err != nil {
						return fmt.Errorf("t.Iat: %w", err)
					}
					if nval != nil {
						typed := ucan.UnixTimestamp(*nval)
						t.Iat = &typed
					}

				}

				// t.Iss (did.DID) (struct)
			case "iss":

				if err := t.Iss.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Iss: %w", err)
				}

				// t.Meta (datamodel.Raw) (struct)
			case "meta":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("t.Meta: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("t.Meta: %w", err)
						}
					} else {
						t.Meta = new(datamodel.Raw)
						if err := t.Meta.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Meta pointer: %w", err)
						}
					}
				}

				// t.Nonce ([]uint8) (slice)
			case "nonce":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Nonce: byte array too large")
						}
						return fmt.Errorf("t.Nonce: %w", err)
					}
					if len(bval) > 0 {
						t.Nonce = []uint8(bval)
					}
				}

				// t.Prf ([]cid.Cid) (slice)
			case "prf":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Prf: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Prf: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Prf: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]cid.Cid, 1)
							{

								c, err := jr.ReadCid()
								if err != nil {
									return fmt.Errorf("item[0]: %w", err)
								}
								item[0] = c

							}
							t.Prf = append(t.Prf, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Prf: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Prf: slice too large")
							}
						}
					}

				}

				// t.Sub (did.DID) (struct)
			case "sub":

				if err := t.Sub.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Sub: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("TokenPayloadModel1_0_0_rc1: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: map too large")
			}
		}
	}

	return nil
}
func (t *SigPayloadModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Header ([]uint8) (slice)
	if len("h") > 8192 {
		return fmt.Errorf("String in field \"h\" was too long")
	}
	if err := jw.WriteString(string("h")); err != nil {
		return fmt.Errorf("\"h\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Header) > 2097152 {
		return fmt.Errorf("Byte array in field t.Header was too long")
	}

	if err := jw.WriteBytes(t.Header); err != nil {
		return fmt.Errorf("t.Header: %w", err)
	}

	written++
	if t.TokenPayload1_0_0_rc1 != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.TokenPayload1_0_0_rc1 (datamodel.TokenPayloadModel1_0_0_rc1) (struct)
	if t.TokenPayload1_0_0_rc1 != nil {
		if len("ucan/inv@1.0.0-rc.1") > 8192 {
			return fmt.Errorf("String in field \"ucan/inv@1.0.0-rc.1\" was too long")
		}
		if err := jw.WriteString(string("ucan/inv@1.0.0-rc.1")); err != nil {
			return fmt.Errorf("\"ucan/inv@1.0.0-rc.1\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if err := t.TokenPayload1_0_0_rc1.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("t.TokenPayload1_0_0_rc1: %w", err)
		}
		written++
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *SigPayloadModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = SigPayloadModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("SigPayloadModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("SigPayloadModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("SigPayloadModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("SigPayloadModel: string too large")
				}
				return fmt.Errorf("SigPayloadModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("SigPayloadModel: %w", err)
			}
			switch name {

			// t.Header ([]uint8) (slice)
			case "h":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Header: byte array too large")
						}
						return fmt.Errorf("t.Header: %w", err)
					}
					if len(bval) > 0 {
						t.Header = []uint8(bval)
					}
				}

				// t.TokenPayload1_0_0_rc1 (datamodel.TokenPayloadModel1_0_0_rc1) (struct)
			case "ucan/inv@1.0.0-rc.1":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("t.TokenPayload1_0_0_rc1: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("t.TokenPayload1_0_0_rc1: %w", err)
						}
					} else {
						t.TokenPayload1_0_0_rc1 = new(TokenPayloadModel1_0_0_rc1)
						if err := t.TokenPayload1_0_0_rc1.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.TokenPayload1_0_0_rc1 pointer: %w", err)
						}
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("SigPayloadModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("SigPayloadModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("SigPayloadModel: map too large")
			}
		}
	}

	return nil
}
