// Code generated by fieldgen; DO NOT EDIT.

package fields

import (
	policy "github.com/fil-forge/ucantone/ucan/delegation/policy"
	multihash "github.com/multiformats/go-multihash"
	big "math/big"
)

// BlobFields is the policy field descriptor type for Blob.
type BlobFields struct {
	Digest policy.Selector[multihash.Multihash]
	Size   policy.Selector[uint64]
}

// RetrieveArgsFields is the policy field descriptor type for RetrieveArgs.
type RetrieveArgsFields struct {
	Blob BlobFields
}

// ShardFields is the policy field descriptor type for Shard.
type ShardFields struct {
	Codec policy.Selector[uint64]
}

// ManifestFields is the policy field descriptor type for Manifest.
type ManifestFields struct {
	Name   policy.Selector[string]
	Shards policy.SliceSelector[ShardFields]
}

// SignArgsFields is the policy field descriptor type for SignArgs.
type SignArgsFields struct {
	DataSet policy.Selector[*big.Int]
}

// EnvelopeFields is the policy field descriptor type for Envelope.
type EnvelopeFields struct {
	Primary  BlobFields
	Fallback BlobFields
}

// TaggedFields is the policy field descriptor type for Tagged.
type TaggedFields struct {
	Tags policy.SliceSelector[policy.Selector[string]]
}

// LabelsFields is the policy field descriptor type for Labels.
type LabelsFields struct {
	Meta policy.MapSelector[policy.Selector[string]]
}

// BundleFields is the policy field descriptor type for Bundle.
type BundleFields struct {
	Items policy.SliceSelector[EnvelopeFields]
}

// Blob is the policy field descriptor for Blob.
var Blob = BlobFields{
	Digest: policy.NewSelector[multihash.Multihash](".digest"),
	Size:   policy.NewSelector[uint64](".size"),
}

// RetrieveArgs is the policy field descriptor for RetrieveArgs.
var RetrieveArgs = RetrieveArgsFields{
	Blob: BlobFields{
		Digest: policy.NewSelector[multihash.Multihash](".blob.digest"),
		Size:   policy.NewSelector[uint64](".blob.size"),
	},
}

// Shard is the policy field descriptor for Shard.
var Shard = ShardFields{
	Codec: policy.NewSelector[uint64](".codec"),
}

// Manifest is the policy field descriptor for Manifest.
var Manifest = ManifestFields{
	Name: policy.NewSelector[string](".name"),
	Shards: policy.NewSliceSelector[ShardFields](".shards", ShardFields{
		Codec: policy.NewSelector[uint64](".codec"),
	}),
}

// SignArgs is the policy field descriptor for SignArgs.
var SignArgs = SignArgsFields{
	DataSet: policy.NewSelector[*big.Int](".dataSet"),
}

// Envelope is the policy field descriptor for Envelope.
var Envelope = EnvelopeFields{
	Primary: BlobFields{
		Digest: policy.NewSelector[multihash.Multihash](".primary.digest"),
		Size:   policy.NewSelector[uint64](".primary.size"),
	},
	Fallback: BlobFields{
		Digest: policy.NewSelector[multihash.Multihash](".fallback.digest"),
		Size:   policy.NewSelector[uint64](".fallback.size"),
	},
}

// Tagged is the policy field descriptor for Tagged.
var Tagged = TaggedFields{
	Tags: policy.NewSliceSelector[policy.Selector[string]](".tags", policy.NewSelector[string](".")),
}

// Labels is the policy field descriptor for Labels.
var Labels = LabelsFields{
	Meta: policy.NewMapSelector[policy.Selector[string]](".meta", policy.NewSelector[string](".")),
}

// Bundle is the policy field descriptor for Bundle.
var Bundle = BundleFields{
	Items: policy.NewSliceSelector[EnvelopeFields](".items", EnvelopeFields{
		Primary: BlobFields{
			Digest: policy.NewSelector[multihash.Multihash](".primary.digest"),
			Size:   policy.NewSelector[uint64](".primary.size"),
		},
		Fallback: BlobFields{
			Digest: policy.NewSelector[multihash.Multihash](".fallback.digest"),
			Size:   policy.NewSelector[uint64](".fallback.size"),
		},
	}),
}
