// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *EnvelopeModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("EnvelopeModel: %w", err)
	}

	// t.Signature ([]uint8) (slice)
	if len(t.Signature) > 2097152 {
		return fmt.Errorf("Byte array in field t.Signature was too long")
	}

	if err := jw.WriteBytes(t.Signature); err != nil {
		return fmt.Errorf("t.Signature: %w", err)
	}

	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("SigPayload: %w", err)
	}

	// t.SigPayload (datamodel.Raw) (struct)
	if err := t.SigPayload.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.SigPayload: %w", err)
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("EnvelopeModel: %w", err)
	}
	return nil
}

func (t *EnvelopeModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = EnvelopeModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("EnvelopeModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("EnvelopeModel: %w", err)
	}
	if close {
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("EnvelopeModel: %w", err)
		}
	} else {

		// t.Signature ([]uint8) (slice)

		{
			bval, err := jr.ReadBytes(2097152)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("t.Signature: byte array too large")
				}
				return fmt.Errorf("t.Signature: %w", err)
			}
			if len(bval) > 0 {
				t.Signature = []uint8(bval)
			}
		}

		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("EnvelopeModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 2")
			}
		}

		// t.SigPayload (datamodel.Raw) (struct)

		if err := t.SigPayload.UnmarshalDagJSON(jr); err != nil {
			return fmt.Errorf("unmarshaling t.SigPayload: %w", err)
		}

		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("EnvelopeModel: %w", err)
		}
	}
	return nil
}
