//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	datamodel "github.com/fil-forge/ucantone/ipld/datamodel"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *PolicyModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)

	// t.Statements ([]datamodel.StatementModel) (slice)
	if len(t.Statements) > 8192 {
		return fmt.Errorf("slice value in field t.Statements was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Statements: %w", err)
	}
	for i, v := range t.Statements {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Statements: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Statements: %w", err)
	}

	return nil
}

func (t *PolicyModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = PolicyModel{}

	jr := jsg.NewDagJsonReader(r)

	// t.Statements ([]datamodel.StatementModel) (slice)

	{

		if err := jr.ReadArrayOpen(); err != nil {
			return fmt.Errorf("reading array open for field t.Statements: %w", err)
		}

		close, err := jr.PeekArrayClose()
		if err != nil {
			return fmt.Errorf("peeking array close for field t.Statements: %w", err)
		}
		if close {
			if err := jr.ReadArrayClose(); err != nil {
				return fmt.Errorf("reading array close for field t.Statements: %w", err)
			}

		} else {
			for i := 0; i < 8192; i++ {
				item := make([]StatementModel, 1)

				if err := item[0].UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling item[0]: %w", err)
				}

				t.Statements = append(t.Statements, item[0])

				close, err := jr.ReadArrayCloseOrComma()
				if err != nil {
					return fmt.Errorf("reading array close or comma for field t.Statements: %w", err)
				}
				if close {
					break
				}
				if i == 8192-1 {
					return fmt.Errorf("reading array for field t.Statements: slice too large")
				}
			}
		}

	}
	return nil
}

func (t *ComparisonModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field ComparisonModel: %w", err)
	}

	// t.Op (string) (string)
	if len(t.Op) > 8192 {
		return fmt.Errorf("string in field t.Op was too long")
	}
	if err := jw.WriteString(string(t.Op)); err != nil {
		return fmt.Errorf("writing string for field t.Op: %w", err)
	}
	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Selector: %w", err)
	}

	// t.Selector (string) (string)
	if len(t.Selector) > 8192 {
		return fmt.Errorf("string in field t.Selector was too long")
	}
	if err := jw.WriteString(string(t.Selector)); err != nil {
		return fmt.Errorf("writing string for field t.Selector: %w", err)
	}
	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Value: %w", err)
	}

	// t.Value (datamodel.Any) (struct)
	if err := t.Value.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Value: %w", err)
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field ComparisonModel: %w", err)
	}
	return nil
}

func (t *ComparisonModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ComparisonModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field ComparisonModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field ComparisonModel: %w", err)
	}
	if close {
		return fmt.Errorf("json input has too few fields 0 < 3")
	} else {

		// t.Op (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Op: string too long")
				}
				return fmt.Errorf("reading string for field t.Op: %w", err)
			}
			t.Op = string(sval)
		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field ComparisonModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 3")
			}
		}

		// t.Selector (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Selector: string too long")
				}
				return fmt.Errorf("reading string for field t.Selector: %w", err)
			}
			t.Selector = string(sval)
		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field ComparisonModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 2 < 3")
			}
		}

		// t.Value (datamodel.Any) (struct)

		{
			null, err := jr.PeekNull()
			if err != nil {
				return fmt.Errorf("peeking null for field t.Value: %w", err)
			}
			if null {
				if err := jr.ReadNull(); err != nil {
					return fmt.Errorf("reading null for field t.Value: %w", err)
				}
			} else {
				t.Value = new(datamodel.Any)
				if err := t.Value.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Value pointer: %w", err)
				}
			}
		}

		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field ComparisonModel: %w", err)
		}
	}
	return nil
}

func (t *WildcardModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field WildcardModel: %w", err)
	}

	// t.Op (string) (string)
	if len(t.Op) > 8192 {
		return fmt.Errorf("string in field t.Op was too long")
	}
	if err := jw.WriteString(string(t.Op)); err != nil {
		return fmt.Errorf("writing string for field t.Op: %w", err)
	}
	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Selector: %w", err)
	}

	// t.Selector (string) (string)
	if len(t.Selector) > 8192 {
		return fmt.Errorf("string in field t.Selector was too long")
	}
	if err := jw.WriteString(string(t.Selector)); err != nil {
		return fmt.Errorf("writing string for field t.Selector: %w", err)
	}
	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Pattern: %w", err)
	}

	// t.Pattern (string) (string)
	if len(t.Pattern) > 8192 {
		return fmt.Errorf("string in field t.Pattern was too long")
	}
	if err := jw.WriteString(string(t.Pattern)); err != nil {
		return fmt.Errorf("writing string for field t.Pattern: %w", err)
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field WildcardModel: %w", err)
	}
	return nil
}

func (t *WildcardModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = WildcardModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field WildcardModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field WildcardModel: %w", err)
	}
	if close {
		return fmt.Errorf("json input has too few fields 0 < 3")
	} else {

		// t.Op (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Op: string too long")
				}
				return fmt.Errorf("reading string for field t.Op: %w", err)
			}
			t.Op = string(sval)
		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field WildcardModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 3")
			}
		}

		// t.Selector (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Selector: string too long")
				}
				return fmt.Errorf("reading string for field t.Selector: %w", err)
			}
			t.Selector = string(sval)
		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field WildcardModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 2 < 3")
			}
		}

		// t.Pattern (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Pattern: string too long")
				}
				return fmt.Errorf("reading string for field t.Pattern: %w", err)
			}
			t.Pattern = string(sval)
		}
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field WildcardModel: %w", err)
		}
	}
	return nil
}

func (t *ConjunctionModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field ConjunctionModel: %w", err)
	}

	// t.Op (string) (string)
	if len(t.Op) > 8192 {
		return fmt.Errorf("string in field t.Op was too long")
	}
	if err := jw.WriteString(string(t.Op)); err != nil {
		return fmt.Errorf("writing string for field t.Op: %w", err)
	}
	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Statements: %w", err)
	}

	// t.Statements ([]*datamodel.StatementModel) (slice)
	if len(t.Statements) > 8192 {
		return fmt.Errorf("slice value in field t.Statements was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Statements: %w", err)
	}
	for i, v := range t.Statements {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Statements: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Statements: %w", err)
	}

	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field ConjunctionModel: %w", err)
	}
	return nil
}

func (t *ConjunctionModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ConjunctionModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field ConjunctionModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field ConjunctionModel: %w", err)
	}
	if close {
		return fmt.Errorf("json input has too few fields 0 < 2")
	} else {

		// t.Op (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Op: string too long")
				}
				return fmt.Errorf("reading string for field t.Op: %w", err)
			}
			t.Op = string(sval)
		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field ConjunctionModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 2")
			}
		}

		// t.Statements ([]*datamodel.StatementModel) (slice)

		{

			if err := jr.ReadArrayOpen(); err != nil {
				return fmt.Errorf("reading array open for field t.Statements: %w", err)
			}

			close, err := jr.PeekArrayClose()
			if err != nil {
				return fmt.Errorf("peeking array close for field t.Statements: %w", err)
			}
			if close {
				if err := jr.ReadArrayClose(); err != nil {
					return fmt.Errorf("reading array close for field t.Statements: %w", err)
				}

			} else {
				for i := 0; i < 8192; i++ {
					item := make([]*StatementModel, 1)

					{
						null, err := jr.PeekNull()
						if err != nil {
							return fmt.Errorf("peeking null for field item[0]: %w", err)
						}
						if null {
							if err := jr.ReadNull(); err != nil {
								return fmt.Errorf("reading null for field item[0]: %w", err)
							}
						} else {
							item[0] = new(StatementModel)
							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0] pointer: %w", err)
							}
						}
					}

					t.Statements = append(t.Statements, item[0])

					close, err := jr.ReadArrayCloseOrComma()
					if err != nil {
						return fmt.Errorf("reading array close or comma for field t.Statements: %w", err)
					}
					if close {
						break
					}
					if i == 8192-1 {
						return fmt.Errorf("reading array for field t.Statements: slice too large")
					}
				}
			}

		}
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field ConjunctionModel: %w", err)
		}
	}
	return nil
}

func (t *DisjunctionModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field DisjunctionModel: %w", err)
	}

	// t.Op (string) (string)
	if len(t.Op) > 8192 {
		return fmt.Errorf("string in field t.Op was too long")
	}
	if err := jw.WriteString(string(t.Op)); err != nil {
		return fmt.Errorf("writing string for field t.Op: %w", err)
	}
	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Statements: %w", err)
	}

	// t.Statements ([]*datamodel.StatementModel) (slice)
	if len(t.Statements) > 8192 {
		return fmt.Errorf("slice value in field t.Statements was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.Statements: %w", err)
	}
	for i, v := range t.Statements {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.Statements: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.Statements: %w", err)
	}

	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field DisjunctionModel: %w", err)
	}
	return nil
}

func (t *DisjunctionModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = DisjunctionModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field DisjunctionModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field DisjunctionModel: %w", err)
	}
	if close {
		return fmt.Errorf("json input has too few fields 0 < 2")
	} else {

		// t.Op (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Op: string too long")
				}
				return fmt.Errorf("reading string for field t.Op: %w", err)
			}
			t.Op = string(sval)
		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field DisjunctionModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 2")
			}
		}

		// t.Statements ([]*datamodel.StatementModel) (slice)

		{

			if err := jr.ReadArrayOpen(); err != nil {
				return fmt.Errorf("reading array open for field t.Statements: %w", err)
			}

			close, err := jr.PeekArrayClose()
			if err != nil {
				return fmt.Errorf("peeking array close for field t.Statements: %w", err)
			}
			if close {
				if err := jr.ReadArrayClose(); err != nil {
					return fmt.Errorf("reading array close for field t.Statements: %w", err)
				}

			} else {
				for i := 0; i < 8192; i++ {
					item := make([]*StatementModel, 1)

					{
						null, err := jr.PeekNull()
						if err != nil {
							return fmt.Errorf("peeking null for field item[0]: %w", err)
						}
						if null {
							if err := jr.ReadNull(); err != nil {
								return fmt.Errorf("reading null for field item[0]: %w", err)
							}
						} else {
							item[0] = new(StatementModel)
							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0] pointer: %w", err)
							}
						}
					}

					t.Statements = append(t.Statements, item[0])

					close, err := jr.ReadArrayCloseOrComma()
					if err != nil {
						return fmt.Errorf("reading array close or comma for field t.Statements: %w", err)
					}
					if close {
						break
					}
					if i == 8192-1 {
						return fmt.Errorf("reading array for field t.Statements: slice too large")
					}
				}
			}

		}
		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field DisjunctionModel: %w", err)
		}
	}
	return nil
}

func (t *NegationModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field NegationModel: %w", err)
	}

	// t.Op (string) (string)
	if len(t.Op) > 8192 {
		return fmt.Errorf("string in field t.Op was too long")
	}
	if err := jw.WriteString(string(t.Op)); err != nil {
		return fmt.Errorf("writing string for field t.Op: %w", err)
	}
	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Statement: %w", err)
	}

	// t.Statement (datamodel.StatementModel) (struct)
	if err := t.Statement.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Statement: %w", err)
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field NegationModel: %w", err)
	}
	return nil
}

func (t *NegationModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = NegationModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field NegationModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field NegationModel: %w", err)
	}
	if close {
		return fmt.Errorf("json input has too few fields 0 < 2")
	} else {

		// t.Op (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Op: string too long")
				}
				return fmt.Errorf("reading string for field t.Op: %w", err)
			}
			t.Op = string(sval)
		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field NegationModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 2")
			}
		}

		// t.Statement (datamodel.StatementModel) (struct)

		{
			null, err := jr.PeekNull()
			if err != nil {
				return fmt.Errorf("peeking null for field t.Statement: %w", err)
			}
			if null {
				if err := jr.ReadNull(); err != nil {
					return fmt.Errorf("reading null for field t.Statement: %w", err)
				}
			} else {
				t.Statement = new(StatementModel)
				if err := t.Statement.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Statement pointer: %w", err)
				}
			}
		}

		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field NegationModel: %w", err)
		}
	}
	return nil
}

func (t *QuantificationModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field QuantificationModel: %w", err)
	}

	// t.Op (string) (string)
	if len(t.Op) > 8192 {
		return fmt.Errorf("string in field t.Op was too long")
	}
	if err := jw.WriteString(string(t.Op)); err != nil {
		return fmt.Errorf("writing string for field t.Op: %w", err)
	}
	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Selector: %w", err)
	}

	// t.Selector (string) (string)
	if len(t.Selector) > 8192 {
		return fmt.Errorf("string in field t.Selector was too long")
	}
	if err := jw.WriteString(string(t.Selector)); err != nil {
		return fmt.Errorf("writing string for field t.Selector: %w", err)
	}
	if err := jw.WriteComma(); err != nil {
		return fmt.Errorf("writing comma for field Statement: %w", err)
	}

	// t.Statement (datamodel.StatementModel) (struct)
	if err := t.Statement.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("marshaling field t.Statement: %w", err)
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field QuantificationModel: %w", err)
	}
	return nil
}

func (t *QuantificationModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = QuantificationModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadArrayOpen(); err != nil {
		return fmt.Errorf("reading array open for field QuantificationModel: %w", err)
	}
	close, err := jr.PeekArrayClose()
	if err != nil {
		return fmt.Errorf("peeking array close for field QuantificationModel: %w", err)
	}
	if close {
		return fmt.Errorf("json input has too few fields 0 < 3")
	} else {

		// t.Op (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Op: string too long")
				}
				return fmt.Errorf("reading string for field t.Op: %w", err)
			}
			t.Op = string(sval)
		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field QuantificationModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 1 < 3")
			}
		}

		// t.Selector (string) (string)

		{
			sval, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field t.Selector: string too long")
				}
				return fmt.Errorf("reading string for field t.Selector: %w", err)
			}
			t.Selector = string(sval)
		}
		{
			close, err := jr.ReadArrayCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading array close or comma for field QuantificationModel: %w", err)
			}
			if close {
				return fmt.Errorf("json input has too few fields 2 < 3")
			}
		}

		// t.Statement (datamodel.StatementModel) (struct)

		{
			null, err := jr.PeekNull()
			if err != nil {
				return fmt.Errorf("peeking null for field t.Statement: %w", err)
			}
			if null {
				if err := jr.ReadNull(); err != nil {
					return fmt.Errorf("reading null for field t.Statement: %w", err)
				}
			} else {
				t.Statement = new(StatementModel)
				if err := t.Statement.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Statement pointer: %w", err)
				}
			}
		}

		if err := jr.ReadArrayClose(); err != nil {
			return fmt.Errorf("reading array close for field QuantificationModel: %w", err)
		}
	}
	return nil
}
