// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	policy "github.com/fil-forge/ucantone/ucan/delegation/policy"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *FixtureModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Args (typegen.Deferred) (struct)
	if len("args") > 8192 {
		return fmt.Errorf("String in field \"args\" was too long")
	}
	if err := jw.WriteString(string("args")); err != nil {
		return fmt.Errorf("\"args\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Args.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Args: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Policies ([]policy.Policy) (slice)
	if len("policies") > 8192 {
		return fmt.Errorf("String in field \"policies\" was too long")
	}
	if err := jw.WriteString(string("policies")); err != nil {
		return fmt.Errorf("\"policies\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Policies) > 8192 {
		return fmt.Errorf("Slice value in field t.Policies was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Policies: %w", err)
	}
	for i, v := range t.Policies {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Policies: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Policies: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *FixtureModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = FixtureModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("FixtureModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("FixtureModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("FixtureModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("FixtureModel: string too large")
				}
				return fmt.Errorf("FixtureModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("FixtureModel: %w", err)
			}
			switch name {

			// t.Args (typegen.Deferred) (struct)
			case "args":

				if err := t.Args.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("failed to read deferred field: %w", err)
				}

				// t.Policies ([]policy.Policy) (slice)
			case "policies":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Policies: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Policies: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Policies: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]policy.Policy, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Policies = append(t.Policies, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Policies: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Policies: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("FixtureModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("FixtureModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("FixtureModel: map too large")
			}
		}
	}

	return nil
}
func (t *FixturesModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Invalid ([]datamodel.FixtureModel) (slice)
	if len("invalid") > 8192 {
		return fmt.Errorf("String in field \"invalid\" was too long")
	}
	if err := jw.WriteString(string("invalid")); err != nil {
		return fmt.Errorf("\"invalid\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Invalid) > 8192 {
		return fmt.Errorf("Slice value in field t.Invalid was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Invalid: %w", err)
	}
	for i, v := range t.Invalid {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Invalid: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Invalid: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Valid ([]datamodel.FixtureModel) (slice)
	if len("valid") > 8192 {
		return fmt.Errorf("String in field \"valid\" was too long")
	}
	if err := jw.WriteString(string("valid")); err != nil {
		return fmt.Errorf("\"valid\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Valid) > 8192 {
		return fmt.Errorf("Slice value in field t.Valid was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Valid: %w", err)
	}
	for i, v := range t.Valid {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Valid: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Valid: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *FixturesModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = FixturesModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("FixturesModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("FixturesModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("FixturesModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("FixturesModel: string too large")
				}
				return fmt.Errorf("FixturesModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("FixturesModel: %w", err)
			}
			switch name {

			// t.Invalid ([]datamodel.FixtureModel) (slice)
			case "invalid":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Invalid: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Invalid: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Invalid: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]FixtureModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Invalid = append(t.Invalid, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Invalid: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Invalid: slice too large")
							}
						}
					}

				}

				// t.Valid ([]datamodel.FixtureModel) (slice)
			case "valid":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Valid: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Valid: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Valid: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]FixtureModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Valid = append(t.Valid, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Valid: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Valid: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("FixturesModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("FixturesModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("FixturesModel: map too large")
			}
		}
	}

	return nil
}
