// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *ErrorModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Name (string) (string)
	if len("name") > 8192 {
		return fmt.Errorf("String in field \"name\" was too long")
	}
	if err := jw.WriteString(string("name")); err != nil {
		return fmt.Errorf("\"name\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Name) > 8192 {
		return fmt.Errorf("String in field t.Name was too long")
	}
	if err := jw.WriteString(string(t.Name)); err != nil {
		return fmt.Errorf("t.Name: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ErrorModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ErrorModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ErrorModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ErrorModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ErrorModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ErrorModel: string too large")
				}
				return fmt.Errorf("ErrorModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ErrorModel: %w", err)
			}
			switch name {

			// t.Name (string) (string)
			case "name":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Name: string too long")
						}
						return fmt.Errorf("t.Name: %w", err)
					}
					t.Name = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ErrorModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ErrorModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ErrorModel: map too large")
			}
		}
	}

	return nil
}
func (t *FixturesModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Comments (string) (string)
	if len("comments") > 8192 {
		return fmt.Errorf("String in field \"comments\" was too long")
	}
	if err := jw.WriteString(string("comments")); err != nil {
		return fmt.Errorf("\"comments\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Comments) > 8192 {
		return fmt.Errorf("String in field t.Comments was too long")
	}
	if err := jw.WriteString(string(t.Comments)); err != nil {
		return fmt.Errorf("t.Comments: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Invalid ([]datamodel.InvalidModel) (slice)
	if len("invalid") > 8192 {
		return fmt.Errorf("String in field \"invalid\" was too long")
	}
	if err := jw.WriteString(string("invalid")); err != nil {
		return fmt.Errorf("\"invalid\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Invalid) > 8192 {
		return fmt.Errorf("Slice value in field t.Invalid was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Invalid: %w", err)
	}
	for i, v := range t.Invalid {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Invalid: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Invalid: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Valid ([]datamodel.ValidModel) (slice)
	if len("valid") > 8192 {
		return fmt.Errorf("String in field \"valid\" was too long")
	}
	if err := jw.WriteString(string("valid")); err != nil {
		return fmt.Errorf("\"valid\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Valid) > 8192 {
		return fmt.Errorf("Slice value in field t.Valid was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Valid: %w", err)
	}
	for i, v := range t.Valid {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Valid: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Valid: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Version (string) (string)
	if len("version") > 8192 {
		return fmt.Errorf("String in field \"version\" was too long")
	}
	if err := jw.WriteString(string("version")); err != nil {
		return fmt.Errorf("\"version\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Version) > 8192 {
		return fmt.Errorf("String in field t.Version was too long")
	}
	if err := jw.WriteString(string(t.Version)); err != nil {
		return fmt.Errorf("t.Version: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *FixturesModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = FixturesModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("FixturesModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("FixturesModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("FixturesModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("FixturesModel: string too large")
				}
				return fmt.Errorf("FixturesModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("FixturesModel: %w", err)
			}
			switch name {

			// t.Comments (string) (string)
			case "comments":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Comments: string too long")
						}
						return fmt.Errorf("t.Comments: %w", err)
					}
					t.Comments = string(sval)
				}

				// t.Invalid ([]datamodel.InvalidModel) (slice)
			case "invalid":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Invalid: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Invalid: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Invalid: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]InvalidModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Invalid = append(t.Invalid, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Invalid: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Invalid: slice too large")
							}
						}
					}

				}

				// t.Valid ([]datamodel.ValidModel) (slice)
			case "valid":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Valid: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Valid: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Valid: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]ValidModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Valid = append(t.Valid, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Valid: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Valid: slice too large")
							}
						}
					}

				}

				// t.Version (string) (string)
			case "version":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Version: string too long")
						}
						return fmt.Errorf("t.Version: %w", err)
					}
					t.Version = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("FixturesModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("FixturesModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("FixturesModel: map too large")
			}
		}
	}

	return nil
}
func (t *InvalidModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Description (string) (string)
	if len("description") > 8192 {
		return fmt.Errorf("String in field \"description\" was too long")
	}
	if err := jw.WriteString(string("description")); err != nil {
		return fmt.Errorf("\"description\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Description) > 8192 {
		return fmt.Errorf("String in field t.Description was too long")
	}
	if err := jw.WriteString(string(t.Description)); err != nil {
		return fmt.Errorf("t.Description: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Error (datamodel.ErrorModel) (struct)
	if len("error") > 8192 {
		return fmt.Errorf("String in field \"error\" was too long")
	}
	if err := jw.WriteString(string("error")); err != nil {
		return fmt.Errorf("\"error\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Error.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Error: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Invocation ([]uint8) (slice)
	if len("invocation") > 8192 {
		return fmt.Errorf("String in field \"invocation\" was too long")
	}
	if err := jw.WriteString(string("invocation")); err != nil {
		return fmt.Errorf("\"invocation\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Invocation) > 2097152 {
		return fmt.Errorf("Byte array in field t.Invocation was too long")
	}

	if err := jw.WriteBytes(t.Invocation); err != nil {
		return fmt.Errorf("t.Invocation: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Name (string) (string)
	if len("name") > 8192 {
		return fmt.Errorf("String in field \"name\" was too long")
	}
	if err := jw.WriteString(string("name")); err != nil {
		return fmt.Errorf("\"name\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Name) > 8192 {
		return fmt.Errorf("String in field t.Name was too long")
	}
	if err := jw.WriteString(string(t.Name)); err != nil {
		return fmt.Errorf("t.Name: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Proofs ([][]uint8) (slice)
	if len("proofs") > 8192 {
		return fmt.Errorf("String in field \"proofs\" was too long")
	}
	if err := jw.WriteString(string("proofs")); err != nil {
		return fmt.Errorf("\"proofs\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Proofs) > 8192 {
		return fmt.Errorf("Slice value in field t.Proofs was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Proofs: %w", err)
	}
	for i, v := range t.Proofs {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Proofs: %w", err)
			}
		}
		if len(v) > 2097152 {
			return fmt.Errorf("Byte array in field v was too long")
		}

		if err := jw.WriteBytes(v); err != nil {
			return fmt.Errorf("v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Proofs: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Time (int64) (int64)
	if len("time") > 8192 {
		return fmt.Errorf("String in field \"time\" was too long")
	}
	if err := jw.WriteString(string("time")); err != nil {
		return fmt.Errorf("\"time\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Time)); err != nil {
		return fmt.Errorf("t.Time: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *InvalidModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = InvalidModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("InvalidModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("InvalidModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("InvalidModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("InvalidModel: string too large")
				}
				return fmt.Errorf("InvalidModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("InvalidModel: %w", err)
			}
			switch name {

			// t.Description (string) (string)
			case "description":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Description: string too long")
						}
						return fmt.Errorf("t.Description: %w", err)
					}
					t.Description = string(sval)
				}

				// t.Error (datamodel.ErrorModel) (struct)
			case "error":

				if err := t.Error.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Error: %w", err)
				}

				// t.Invocation ([]uint8) (slice)
			case "invocation":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Invocation: byte array too large")
						}
						return fmt.Errorf("t.Invocation: %w", err)
					}
					if len(bval) > 0 {
						t.Invocation = []uint8(bval)
					}
				}

				// t.Name (string) (string)
			case "name":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Name: string too long")
						}
						return fmt.Errorf("t.Name: %w", err)
					}
					t.Name = string(sval)
				}

				// t.Proofs ([][]uint8) (slice)
			case "proofs":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Proofs: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Proofs: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Proofs: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([][]uint8, 1)

							{
								bval, err := jr.ReadBytes(2097152)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("item[0]: byte array too large")
									}
									return fmt.Errorf("item[0]: %w", err)
								}
								if len(bval) > 0 {
									item[0] = []uint8(bval)
								}
							}

							t.Proofs = append(t.Proofs, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Proofs: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Proofs: slice too large")
							}
						}
					}

				}

				// t.Time (int64) (int64)
			case "time":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("t.Time: %w", err)
					}
					t.Time = int64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("InvalidModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("InvalidModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("InvalidModel: map too large")
			}
		}
	}

	return nil
}
func (t *ValidModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Description (string) (string)
	if len("description") > 8192 {
		return fmt.Errorf("String in field \"description\" was too long")
	}
	if err := jw.WriteString(string("description")); err != nil {
		return fmt.Errorf("\"description\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Description) > 8192 {
		return fmt.Errorf("String in field t.Description was too long")
	}
	if err := jw.WriteString(string(t.Description)); err != nil {
		return fmt.Errorf("t.Description: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Invocation ([]uint8) (slice)
	if len("invocation") > 8192 {
		return fmt.Errorf("String in field \"invocation\" was too long")
	}
	if err := jw.WriteString(string("invocation")); err != nil {
		return fmt.Errorf("\"invocation\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Invocation) > 2097152 {
		return fmt.Errorf("Byte array in field t.Invocation was too long")
	}

	if err := jw.WriteBytes(t.Invocation); err != nil {
		return fmt.Errorf("t.Invocation: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Name (string) (string)
	if len("name") > 8192 {
		return fmt.Errorf("String in field \"name\" was too long")
	}
	if err := jw.WriteString(string("name")); err != nil {
		return fmt.Errorf("\"name\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Name) > 8192 {
		return fmt.Errorf("String in field t.Name was too long")
	}
	if err := jw.WriteString(string(t.Name)); err != nil {
		return fmt.Errorf("t.Name: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Proofs ([][]uint8) (slice)
	if len("proofs") > 8192 {
		return fmt.Errorf("String in field \"proofs\" was too long")
	}
	if err := jw.WriteString(string("proofs")); err != nil {
		return fmt.Errorf("\"proofs\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Proofs) > 8192 {
		return fmt.Errorf("Slice value in field t.Proofs was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Proofs: %w", err)
	}
	for i, v := range t.Proofs {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Proofs: %w", err)
			}
		}
		if len(v) > 2097152 {
			return fmt.Errorf("Byte array in field v was too long")
		}

		if err := jw.WriteBytes(v); err != nil {
			return fmt.Errorf("v: %w", err)
		}

	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Proofs: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Time (int64) (int64)
	if len("time") > 8192 {
		return fmt.Errorf("String in field \"time\" was too long")
	}
	if err := jw.WriteString(string("time")); err != nil {
		return fmt.Errorf("\"time\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteInt64(int64(t.Time)); err != nil {
		return fmt.Errorf("t.Time: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ValidModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ValidModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ValidModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ValidModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ValidModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ValidModel: string too large")
				}
				return fmt.Errorf("ValidModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ValidModel: %w", err)
			}
			switch name {

			// t.Description (string) (string)
			case "description":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Description: string too long")
						}
						return fmt.Errorf("t.Description: %w", err)
					}
					t.Description = string(sval)
				}

				// t.Invocation ([]uint8) (slice)
			case "invocation":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Invocation: byte array too large")
						}
						return fmt.Errorf("t.Invocation: %w", err)
					}
					if len(bval) > 0 {
						t.Invocation = []uint8(bval)
					}
				}

				// t.Name (string) (string)
			case "name":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Name: string too long")
						}
						return fmt.Errorf("t.Name: %w", err)
					}
					t.Name = string(sval)
				}

				// t.Proofs ([][]uint8) (slice)
			case "proofs":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Proofs: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Proofs: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Proofs: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([][]uint8, 1)

							{
								bval, err := jr.ReadBytes(2097152)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("item[0]: byte array too large")
									}
									return fmt.Errorf("item[0]: %w", err)
								}
								if len(bval) > 0 {
									item[0] = []uint8(bval)
								}
							}

							t.Proofs = append(t.Proofs, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Proofs: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Proofs: slice too large")
							}
						}
					}

				}

				// t.Time (int64) (int64)
			case "time":
				{

					nval, err := jr.ReadNumberAsInt64()
					if err != nil {
						return fmt.Errorf("t.Time: %w", err)
					}
					t.Time = int64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ValidModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ValidModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ValidModel: map too large")
			}
		}
	}

	return nil
}
