//go:build !codegen

// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package plc

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	did "github.com/fil-forge/ucantone/did"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *Operation) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.AlsoKnownAs ([]string) (slice)
	if len("alsoKnownAs") > 8192 {
		return fmt.Errorf("string in field \"alsoKnownAs\" was too long")
	}
	if err := jw.WriteString(string("alsoKnownAs")); err != nil {
		return fmt.Errorf("writing string for field \"alsoKnownAs\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.AlsoKnownAs) > 8192 {
		return fmt.Errorf("slice value in field t.AlsoKnownAs was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.AlsoKnownAs: %w", err)
	}
	for i, v := range t.AlsoKnownAs {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.AlsoKnownAs: %w", err)
			}
		}
		if len(v) > 8192 {
			return fmt.Errorf("string in field v was too long")
		}
		if err := jw.WriteString(string(v)); err != nil {
			return fmt.Errorf("writing string for field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.AlsoKnownAs: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Previous (string) (string)
	if len("prev") > 8192 {
		return fmt.Errorf("string in field \"prev\" was too long")
	}
	if err := jw.WriteString(string("prev")); err != nil {
		return fmt.Errorf("writing string for field \"prev\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if t.Previous == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.Previous: %w", err)
		}
	} else {
		if len(*t.Previous) > 8192 {
			return fmt.Errorf("string in field t.Previous was too long")
		}
		if err := jw.WriteString(string(*t.Previous)); err != nil {
			return fmt.Errorf("writing string for field t.Previous: %w", err)
		}
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.RotationKeys ([]did.DID) (slice)
	if len("rotationKeys") > 8192 {
		return fmt.Errorf("string in field \"rotationKeys\" was too long")
	}
	if err := jw.WriteString(string("rotationKeys")); err != nil {
		return fmt.Errorf("writing string for field \"rotationKeys\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.RotationKeys) > 8192 {
		return fmt.Errorf("slice value in field t.RotationKeys was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.RotationKeys: %w", err)
	}
	for i, v := range t.RotationKeys {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.RotationKeys: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.RotationKeys: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Services (map[string]plc.Service) (map)
	if len("services") > 8192 {
		return fmt.Errorf("string in field \"services\" was too long")
	}
	if err := jw.WriteString(string("services")); err != nil {
		return fmt.Errorf("writing string for field \"services\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Services) > 4096 {
			return fmt.Errorf("cannot marshal t.Services map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Services: %w", err)
		}

		keys := make([]string, 0, len(t.Services))
		for k := range t.Services {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Services: %w", err)
				}
			}
			v := t.Services[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Services: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Services: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Type (string) (string)
	if len("type") > 8192 {
		return fmt.Errorf("string in field \"type\" was too long")
	}
	if err := jw.WriteString(string("type")); err != nil {
		return fmt.Errorf("writing string for field \"type\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := jw.WriteString("plc_operation"); err != nil {
		return err
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.VerificationMethods (map[string]did.DID) (map)
	if len("verificationMethods") > 8192 {
		return fmt.Errorf("string in field \"verificationMethods\" was too long")
	}
	if err := jw.WriteString(string("verificationMethods")); err != nil {
		return fmt.Errorf("writing string for field \"verificationMethods\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.VerificationMethods) > 4096 {
			return fmt.Errorf("cannot marshal t.VerificationMethods map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.VerificationMethods: %w", err)
		}

		keys := make([]string, 0, len(t.VerificationMethods))
		for k := range t.VerificationMethods {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.VerificationMethods: %w", err)
				}
			}
			v := t.VerificationMethods[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.VerificationMethods: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.VerificationMethods: %w", err)
		}
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Operation) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Operation{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Operation: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Operation: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Operation: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Operation: string too large")
				}
				return fmt.Errorf("reading string for field Operation: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Operation: %w", err)
			}
			switch name {

			// t.AlsoKnownAs ([]string) (slice)
			case "alsoKnownAs":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.AlsoKnownAs: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.AlsoKnownAs: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.AlsoKnownAs: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]string, 1)
							{
								sval, err := jr.ReadString(8192)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading string for field item[0]: string too long")
									}
									return fmt.Errorf("reading string for field item[0]: %w", err)
								}
								item[0] = string(sval)
							}
							t.AlsoKnownAs = append(t.AlsoKnownAs, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.AlsoKnownAs: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.AlsoKnownAs: slice too large")
							}
						}
					}

				}

				// t.Previous (string) (string)
			case "prev":
				{
					sval, err := jr.ReadStringOrNull(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string or null for field t.Previous: string too long")
						}
						return fmt.Errorf("reading string or null for field t.Previous: %w", err)
					}
					if sval != nil {
						t.Previous = (*string)(sval)
					}
				}

				// t.RotationKeys ([]did.DID) (slice)
			case "rotationKeys":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.RotationKeys: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.RotationKeys: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.RotationKeys: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]did.DID, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.RotationKeys = append(t.RotationKeys, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.RotationKeys: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.RotationKeys: slice too large")
							}
						}
					}

				}

				// t.Services (map[string]plc.Service) (map)
			case "services":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Services: %w", err)
				}

				t.Services = map[string]Service{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Services: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Services: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Services: %w", err)
						}
						var v Service

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.Services[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Services: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.Type (string) (string)
			case "type":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Type: string too long")
						}
						return fmt.Errorf("reading string for field t.Type: %w", err)
					}
					t.Type = string(sval)
				}

				// t.VerificationMethods (map[string]did.DID) (map)
			case "verificationMethods":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.VerificationMethods: %w", err)
				}

				t.VerificationMethods = map[string]did.DID{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.VerificationMethods: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.VerificationMethods: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.VerificationMethods: %w", err)
						}
						var v did.DID

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.VerificationMethods[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.VerificationMethods: %w", err)
						}
						if close {
							break
						}
					}
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Operation: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Operation: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Operation")
			}
		}
	}

	return nil
}
func (t *SignedOperation) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.AlsoKnownAs ([]string) (slice)
	if len("alsoKnownAs") > 8192 {
		return fmt.Errorf("string in field \"alsoKnownAs\" was too long")
	}
	if err := jw.WriteString(string("alsoKnownAs")); err != nil {
		return fmt.Errorf("writing string for field \"alsoKnownAs\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.AlsoKnownAs) > 8192 {
		return fmt.Errorf("slice value in field t.AlsoKnownAs was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.AlsoKnownAs: %w", err)
	}
	for i, v := range t.AlsoKnownAs {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.AlsoKnownAs: %w", err)
			}
		}
		if len(v) > 8192 {
			return fmt.Errorf("string in field v was too long")
		}
		if err := jw.WriteString(string(v)); err != nil {
			return fmt.Errorf("writing string for field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.AlsoKnownAs: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Previous (string) (string)
	if len("prev") > 8192 {
		return fmt.Errorf("string in field \"prev\" was too long")
	}
	if err := jw.WriteString(string("prev")); err != nil {
		return fmt.Errorf("writing string for field \"prev\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if t.Previous == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("writing null for field t.Previous: %w", err)
		}
	} else {
		if len(*t.Previous) > 8192 {
			return fmt.Errorf("string in field t.Previous was too long")
		}
		if err := jw.WriteString(string(*t.Previous)); err != nil {
			return fmt.Errorf("writing string for field t.Previous: %w", err)
		}
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.RotationKeys ([]did.DID) (slice)
	if len("rotationKeys") > 8192 {
		return fmt.Errorf("string in field \"rotationKeys\" was too long")
	}
	if err := jw.WriteString(string("rotationKeys")); err != nil {
		return fmt.Errorf("writing string for field \"rotationKeys\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.RotationKeys) > 8192 {
		return fmt.Errorf("slice value in field t.RotationKeys was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("writing array open for field t.RotationKeys: %w", err)
	}
	for i, v := range t.RotationKeys {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("writing comma for field t.RotationKeys: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("marshaling field v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("writing array close for field t.RotationKeys: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Services (map[string]plc.Service) (map)
	if len("services") > 8192 {
		return fmt.Errorf("string in field \"services\" was too long")
	}
	if err := jw.WriteString(string("services")); err != nil {
		return fmt.Errorf("writing string for field \"services\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.Services) > 4096 {
			return fmt.Errorf("cannot marshal t.Services map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.Services: %w", err)
		}

		keys := make([]string, 0, len(t.Services))
		for k := range t.Services {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.Services: %w", err)
				}
			}
			v := t.Services[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.Services: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.Services: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Signature (string) (string)
	if len("sig") > 8192 {
		return fmt.Errorf("string in field \"sig\" was too long")
	}
	if err := jw.WriteString(string("sig")); err != nil {
		return fmt.Errorf("writing string for field \"sig\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Signature) > 8192 {
		return fmt.Errorf("string in field t.Signature was too long")
	}
	if err := jw.WriteString(string(t.Signature)); err != nil {
		return fmt.Errorf("writing string for field t.Signature: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Type (string) (string)
	if len("type") > 8192 {
		return fmt.Errorf("string in field \"type\" was too long")
	}
	if err := jw.WriteString(string("type")); err != nil {
		return fmt.Errorf("writing string for field \"type\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := jw.WriteString("plc_operation"); err != nil {
		return err
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.VerificationMethods (map[string]did.DID) (map)
	if len("verificationMethods") > 8192 {
		return fmt.Errorf("string in field \"verificationMethods\" was too long")
	}
	if err := jw.WriteString(string("verificationMethods")); err != nil {
		return fmt.Errorf("writing string for field \"verificationMethods\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	{
		if len(t.VerificationMethods) > 4096 {
			return fmt.Errorf("cannot marshal t.VerificationMethods map too large")
		}

		if err := jw.WriteObjectOpen(); err != nil {
			return fmt.Errorf("writing object open for field t.VerificationMethods: %w", err)
		}

		keys := make([]string, 0, len(t.VerificationMethods))
		for k := range t.VerificationMethods {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for i, k := range keys {
			if i > 0 {
				if err := jw.WriteComma(); err != nil {
					return fmt.Errorf("writing comma for field t.VerificationMethods: %w", err)
				}
			}
			v := t.VerificationMethods[k]
			if len(k) > 8192 {
				return fmt.Errorf("string in field k was too long")
			}
			if err := jw.WriteString(string(k)); err != nil {
				return fmt.Errorf("writing string for field k: %w", err)
			}
			if err := jw.WriteObjectColon(); err != nil {
				return fmt.Errorf("writing colon for field t.VerificationMethods: %w", err)
			}

			if err := v.MarshalDagJSON(jw); err != nil {
				return fmt.Errorf("marshaling field v: %w", err)
			}
		}
		if err := jw.WriteObjectClose(); err != nil {
			return fmt.Errorf("writing object close for field t.VerificationMethods: %w", err)
		}
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *SignedOperation) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = SignedOperation{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for SignedOperation: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for SignedOperation: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for SignedOperation: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field SignedOperation: string too large")
				}
				return fmt.Errorf("reading string for field SignedOperation: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field SignedOperation: %w", err)
			}
			switch name {

			// t.AlsoKnownAs ([]string) (slice)
			case "alsoKnownAs":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.AlsoKnownAs: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.AlsoKnownAs: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.AlsoKnownAs: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]string, 1)
							{
								sval, err := jr.ReadString(8192)
								if err != nil {
									if errors.Is(err, jsg.ErrLimitExceeded) {
										return fmt.Errorf("reading string for field item[0]: string too long")
									}
									return fmt.Errorf("reading string for field item[0]: %w", err)
								}
								item[0] = string(sval)
							}
							t.AlsoKnownAs = append(t.AlsoKnownAs, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.AlsoKnownAs: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.AlsoKnownAs: slice too large")
							}
						}
					}

				}

				// t.Previous (string) (string)
			case "prev":
				{
					sval, err := jr.ReadStringOrNull(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string or null for field t.Previous: string too long")
						}
						return fmt.Errorf("reading string or null for field t.Previous: %w", err)
					}
					if sval != nil {
						t.Previous = (*string)(sval)
					}
				}

				// t.RotationKeys ([]did.DID) (slice)
			case "rotationKeys":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("reading array open for field t.RotationKeys: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("peeking array close for field t.RotationKeys: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("reading array close for field t.RotationKeys: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]did.DID, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.RotationKeys = append(t.RotationKeys, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("reading array close or comma for field t.RotationKeys: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("reading array for field t.RotationKeys: slice too large")
							}
						}
					}

				}

				// t.Services (map[string]plc.Service) (map)
			case "services":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.Services: %w", err)
				}

				t.Services = map[string]Service{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.Services: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.Services: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.Services: %w", err)
						}
						var v Service

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.Services[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.Services: %w", err)
						}
						if close {
							break
						}
					}
				}

				// t.Signature (string) (string)
			case "sig":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Signature: string too long")
						}
						return fmt.Errorf("reading string for field t.Signature: %w", err)
					}
					t.Signature = string(sval)
				}

				// t.Type (string) (string)
			case "type":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Type: string too long")
						}
						return fmt.Errorf("reading string for field t.Type: %w", err)
					}
					t.Type = string(sval)
				}

				// t.VerificationMethods (map[string]did.DID) (map)
			case "verificationMethods":
				if err := jr.ReadObjectOpen(); err != nil {
					return fmt.Errorf("reading object open for field t.VerificationMethods: %w", err)
				}

				t.VerificationMethods = map[string]did.DID{}

				close, err := jr.PeekObjectClose()
				if err != nil {
					return fmt.Errorf("peeking object close for field t.VerificationMethods: %w", err)
				}
				if close {
					if err := jr.ReadObjectClose(); err != nil {
						return fmt.Errorf("reading object close for field t.VerificationMethods: %w", err)
					}
				} else {
					for i, l := 0, 8192; i < l; i++ {
						var k string
						{
							sval, err := jr.ReadString(8192)
							if err != nil {
								if errors.Is(err, jsg.ErrLimitExceeded) {
									return fmt.Errorf("reading string for field k: string too long")
								}
								return fmt.Errorf("reading string for field k: %w", err)
							}
							k = string(sval)
						}
						if err := jr.ReadObjectColon(); err != nil {
							return fmt.Errorf("reading object colon for field t.VerificationMethods: %w", err)
						}
						var v did.DID

						if err := v.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling v: %w", err)
						}

						t.VerificationMethods[k] = v
						close, err := jr.ReadObjectCloseOrComma()
						if err != nil {
							return fmt.Errorf("reading object close or comma for field t.VerificationMethods: %w", err)
						}
						if close {
							break
						}
					}
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for SignedOperation: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field SignedOperation: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for SignedOperation")
			}
		}
	}

	return nil
}
func (t *Service) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return fmt.Errorf("string in field \"endpoint\" was too long")
	}
	if err := jw.WriteString(string("endpoint")); err != nil {
		return fmt.Errorf("writing string for field \"endpoint\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Endpoint) > 8192 {
		return fmt.Errorf("string in field t.Endpoint was too long")
	}
	if err := jw.WriteString(string(t.Endpoint)); err != nil {
		return fmt.Errorf("writing string for field t.Endpoint: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Type (string) (string)
	if len("type") > 8192 {
		return fmt.Errorf("string in field \"type\" was too long")
	}
	if err := jw.WriteString(string("type")); err != nil {
		return fmt.Errorf("writing string for field \"type\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Type) > 8192 {
		return fmt.Errorf("string in field t.Type was too long")
	}
	if err := jw.WriteString(string(t.Type)); err != nil {
		return fmt.Errorf("writing string for field t.Type: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Service) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Service{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Service: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Service: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Service: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Service: string too large")
				}
				return fmt.Errorf("reading string for field Service: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Service: %w", err)
			}
			switch name {

			// t.Endpoint (string) (string)
			case "endpoint":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Endpoint: string too long")
						}
						return fmt.Errorf("reading string for field t.Endpoint: %w", err)
					}
					t.Endpoint = string(sval)
				}

				// t.Type (string) (string)
			case "type":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Type: string too long")
						}
						return fmt.Errorf("reading string for field t.Type: %w", err)
					}
					t.Type = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Service: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Service: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Service")
			}
		}
	}

	return nil
}
func (t *Tombstone) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Previous (string) (string)
	if len("prev") > 8192 {
		return fmt.Errorf("string in field \"prev\" was too long")
	}
	if err := jw.WriteString(string("prev")); err != nil {
		return fmt.Errorf("writing string for field \"prev\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Previous) > 8192 {
		return fmt.Errorf("string in field t.Previous was too long")
	}
	if err := jw.WriteString(string(t.Previous)); err != nil {
		return fmt.Errorf("writing string for field t.Previous: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Type (string) (string)
	if len("type") > 8192 {
		return fmt.Errorf("string in field \"type\" was too long")
	}
	if err := jw.WriteString(string("type")); err != nil {
		return fmt.Errorf("writing string for field \"type\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := jw.WriteString("plc_tombstone"); err != nil {
		return err
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *Tombstone) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = Tombstone{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for Tombstone: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for Tombstone: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for Tombstone: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field Tombstone: string too large")
				}
				return fmt.Errorf("reading string for field Tombstone: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field Tombstone: %w", err)
			}
			switch name {

			// t.Previous (string) (string)
			case "prev":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Previous: string too long")
						}
						return fmt.Errorf("reading string for field t.Previous: %w", err)
					}
					t.Previous = string(sval)
				}

				// t.Type (string) (string)
			case "type":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Type: string too long")
						}
						return fmt.Errorf("reading string for field t.Type: %w", err)
					}
					t.Type = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for Tombstone: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field Tombstone: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for Tombstone")
			}
		}
	}

	return nil
}
func (t *SignedTombstone) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Previous (string) (string)
	if len("prev") > 8192 {
		return fmt.Errorf("string in field \"prev\" was too long")
	}
	if err := jw.WriteString(string("prev")); err != nil {
		return fmt.Errorf("writing string for field \"prev\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Previous) > 8192 {
		return fmt.Errorf("string in field t.Previous was too long")
	}
	if err := jw.WriteString(string(t.Previous)); err != nil {
		return fmt.Errorf("writing string for field t.Previous: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Signature (string) (string)
	if len("sig") > 8192 {
		return fmt.Errorf("string in field \"sig\" was too long")
	}
	if err := jw.WriteString(string("sig")); err != nil {
		return fmt.Errorf("writing string for field \"sig\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Signature) > 8192 {
		return fmt.Errorf("string in field t.Signature was too long")
	}
	if err := jw.WriteString(string(t.Signature)); err != nil {
		return fmt.Errorf("writing string for field t.Signature: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Type (string) (string)
	if len("type") > 8192 {
		return fmt.Errorf("string in field \"type\" was too long")
	}
	if err := jw.WriteString(string("type")); err != nil {
		return fmt.Errorf("writing string for field \"type\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := jw.WriteString("plc_tombstone"); err != nil {
		return err
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *SignedTombstone) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = SignedTombstone{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("reading object open for SignedTombstone: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("peeking object close for SignedTombstone: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("reading object close for SignedTombstone: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("reading string for field SignedTombstone: string too large")
				}
				return fmt.Errorf("reading string for field SignedTombstone: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("reading object colon for field SignedTombstone: %w", err)
			}
			switch name {

			// t.Previous (string) (string)
			case "prev":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Previous: string too long")
						}
						return fmt.Errorf("reading string for field t.Previous: %w", err)
					}
					t.Previous = string(sval)
				}

				// t.Signature (string) (string)
			case "sig":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Signature: string too long")
						}
						return fmt.Errorf("reading string for field t.Signature: %w", err)
					}
					t.Signature = string(sval)
				}

				// t.Type (string) (string)
			case "type":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("reading string for field t.Type: string too long")
						}
						return fmt.Errorf("reading string for field t.Type: %w", err)
					}
					t.Type = string(sval)
				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ignoring field %s for SignedTombstone: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("reading object close or comma for field SignedTombstone: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("map too large for SignedTombstone")
			}
		}
	}

	return nil
}
