// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package datamodel

import (
	"fmt"
	"io"
	"math"
	"sort"

	datamodel "github.com/fil-forge/ucantone/ipld/datamodel"
	command "github.com/fil-forge/ucantone/ucan/command"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *TokenPayloadModel1_0_0_rc1) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 9

	if t.Meta == nil {
		fieldCount--
	}

	if t.Nbf == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Aud (did.DID) (struct)
	if len("aud") > 8192 {
		return xerrors.Errorf("Value in field \"aud\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("aud"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("aud")); err != nil {
		return err
	}

	if err := t.Aud.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Cmd (command.Command) (string)
	if len("cmd") > 8192 {
		return xerrors.Errorf("Value in field \"cmd\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("cmd"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("cmd")); err != nil {
		return err
	}

	if len(t.Cmd) > 8192 {
		return xerrors.Errorf("Value in field t.Cmd was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Cmd))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Cmd)); err != nil {
		return err
	}

	// t.Exp (uint64) (uint64)
	if len("exp") > 8192 {
		return xerrors.Errorf("Value in field \"exp\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("exp"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("exp")); err != nil {
		return err
	}

	if t.Exp == nil {
		if _, err := cw.Write(cbg.CborNull); err != nil {
			return err
		}
	} else {
		if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(*t.Exp)); err != nil {
			return err
		}
	}

	// t.Iss (did.DID) (struct)
	if len("iss") > 8192 {
		return xerrors.Errorf("Value in field \"iss\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("iss"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("iss")); err != nil {
		return err
	}

	if err := t.Iss.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Nbf (uint64) (uint64)
	if t.Nbf != nil {

		if len("nbf") > 8192 {
			return xerrors.Errorf("Value in field \"nbf\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("nbf"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("nbf")); err != nil {
			return err
		}

		if t.Nbf == nil {
			if _, err := cw.Write(cbg.CborNull); err != nil {
				return err
			}
		} else {
			if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(*t.Nbf)); err != nil {
				return err
			}
		}

	}

	// t.Pol (policy.Policy) (struct)
	if len("pol") > 8192 {
		return xerrors.Errorf("Value in field \"pol\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("pol"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("pol")); err != nil {
		return err
	}

	if err := t.Pol.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Sub (did.DID) (struct)
	if len("sub") > 8192 {
		return xerrors.Errorf("Value in field \"sub\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("sub"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("sub")); err != nil {
		return err
	}

	if err := t.Sub.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Meta (datamodel.MapWrapper) (struct)
	if t.Meta != nil {

		if len("meta") > 8192 {
			return xerrors.Errorf("Value in field \"meta\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("meta"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("meta")); err != nil {
			return err
		}

		if err := t.Meta.MarshalCBOR(cw); err != nil {
			return err
		}
	}

	// t.Nonce ([]uint8) (slice)
	if len("nonce") > 8192 {
		return xerrors.Errorf("Value in field \"nonce\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("nonce"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("nonce")); err != nil {
		return err
	}

	if len(t.Nonce) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Nonce was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Nonce))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Nonce); err != nil {
		return err
	}

	return nil
}

func (t *TokenPayloadModel1_0_0_rc1) UnmarshalCBOR(r io.Reader) (err error) {
	*t = TokenPayloadModel1_0_0_rc1{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("TokenPayloadModel1_0_0_rc1: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 5)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Aud (did.DID) (struct)
		case "aud":

			{

				if err := t.Aud.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Aud: %w", err)
				}

			}
			// t.Cmd (command.Command) (string)
		case "cmd":

			{
				sval, err := cbg.ReadStringWithMax(cr, 8192)
				if err != nil {
					return err
				}

				t.Cmd = command.Command(sval)
			}
			// t.Exp (uint64) (uint64)
		case "exp":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					maj, extra, err = cr.ReadHeader()
					if err != nil {
						return err
					}
					if maj != cbg.MajUnsignedInt {
						return fmt.Errorf("wrong type for uint64 field")
					}
					typed := uint64(extra)
					t.Exp = &typed
				}

			}
			// t.Iss (did.DID) (struct)
		case "iss":

			{

				if err := t.Iss.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Iss: %w", err)
				}

			}
			// t.Nbf (uint64) (uint64)
		case "nbf":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					maj, extra, err = cr.ReadHeader()
					if err != nil {
						return err
					}
					if maj != cbg.MajUnsignedInt {
						return fmt.Errorf("wrong type for uint64 field")
					}
					typed := uint64(extra)
					t.Nbf = &typed
				}

			}
			// t.Pol (policy.Policy) (struct)
		case "pol":

			{

				if err := t.Pol.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Pol: %w", err)
				}

			}
			// t.Sub (did.DID) (struct)
		case "sub":

			{

				if err := t.Sub.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Sub: %w", err)
				}

			}
			// t.Meta (datamodel.MapWrapper) (struct)
		case "meta":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					t.Meta = new(datamodel.MapWrapper)
					if err := t.Meta.UnmarshalCBOR(cr); err != nil {
						return xerrors.Errorf("unmarshaling t.Meta pointer: %w", err)
					}
				}

			}
			// t.Nonce ([]uint8) (slice)
		case "nonce":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Nonce: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Nonce = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Nonce); err != nil {
				return err
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *SigPayloadModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)
	fieldCount := 2

	if t.TokenPayload1_0_0_rc1 == nil {
		fieldCount--
	}

	if _, err := cw.Write(cbg.CborEncodeMajorType(cbg.MajMap, uint64(fieldCount))); err != nil {
		return err
	}

	// t.Header ([]uint8) (slice)
	if len("h") > 8192 {
		return xerrors.Errorf("Value in field \"h\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("h"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("h")); err != nil {
		return err
	}

	if len(t.Header) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Header was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Header))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Header); err != nil {
		return err
	}

	// t.TokenPayload1_0_0_rc1 (datamodel.TokenPayloadModel1_0_0_rc1) (struct)
	if t.TokenPayload1_0_0_rc1 != nil {

		if len("ucan/dlg@1.0.0-rc.1") > 8192 {
			return xerrors.Errorf("Value in field \"ucan/dlg@1.0.0-rc.1\" was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("ucan/dlg@1.0.0-rc.1"))); err != nil {
			return err
		}
		if _, err := cw.WriteString(string("ucan/dlg@1.0.0-rc.1")); err != nil {
			return err
		}

		if err := t.TokenPayload1_0_0_rc1.MarshalCBOR(cw); err != nil {
			return err
		}
	}
	return nil
}

func (t *SigPayloadModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = SigPayloadModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("SigPayloadModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 19)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Header ([]uint8) (slice)
		case "h":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.Header: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.Header = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.Header); err != nil {
				return err
			}

			// t.TokenPayload1_0_0_rc1 (datamodel.TokenPayloadModel1_0_0_rc1) (struct)
		case "ucan/dlg@1.0.0-rc.1":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}
					t.TokenPayload1_0_0_rc1 = new(TokenPayloadModel1_0_0_rc1)
					if err := t.TokenPayload1_0_0_rc1.UnmarshalCBOR(cr); err != nil {
						return xerrors.Errorf("unmarshaling t.TokenPayload1_0_0_rc1 pointer: %w", err)
					}
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
