// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	datamodel "github.com/fil-forge/ucantone/ipld/datamodel"
	ucan "github.com/fil-forge/ucantone/ucan"
	command "github.com/fil-forge/ucantone/ucan/command"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *TokenPayloadModel1_0_0_rc1) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Aud (did.DID) (struct)
	if len("aud") > 8192 {
		return fmt.Errorf("String in field \"aud\" was too long")
	}
	if err := jw.WriteString(string("aud")); err != nil {
		return fmt.Errorf("\"aud\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Aud.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Aud: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Cmd (command.Command) (string)
	if len("cmd") > 8192 {
		return fmt.Errorf("String in field \"cmd\" was too long")
	}
	if err := jw.WriteString(string("cmd")); err != nil {
		return fmt.Errorf("\"cmd\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Cmd) > 8192 {
		return fmt.Errorf("String in field t.Cmd was too long")
	}
	if err := jw.WriteString(string(t.Cmd)); err != nil {
		return fmt.Errorf("t.Cmd: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Exp (ucan.UTCUnixTimestamp) (int64)
	if len("exp") > 8192 {
		return fmt.Errorf("String in field \"exp\" was too long")
	}
	if err := jw.WriteString(string("exp")); err != nil {
		return fmt.Errorf("\"exp\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if t.Exp == nil {
		if err := jw.WriteNull(); err != nil {
			return fmt.Errorf("t.Exp: %w", err)
		}
	} else {
		if err := jw.WriteInt64(int64(*t.Exp)); err != nil {
			return fmt.Errorf("t.Exp: %w", err)
		}
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Iss (did.DID) (struct)
	if len("iss") > 8192 {
		return fmt.Errorf("String in field \"iss\" was too long")
	}
	if err := jw.WriteString(string("iss")); err != nil {
		return fmt.Errorf("\"iss\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Iss.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Iss: %w", err)
	}
	written++
	if t.Meta != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Meta (datamodel.Raw) (struct)
	if t.Meta != nil {
		if len("meta") > 8192 {
			return fmt.Errorf("String in field \"meta\" was too long")
		}
		if err := jw.WriteString(string("meta")); err != nil {
			return fmt.Errorf("\"meta\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if err := t.Meta.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("t.Meta: %w", err)
		}
		written++
	}
	if t.Nbf != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.Nbf (ucan.UTCUnixTimestamp) (int64)
	if t.Nbf != nil {
		if len("nbf") > 8192 {
			return fmt.Errorf("String in field \"nbf\" was too long")
		}
		if err := jw.WriteString(string("nbf")); err != nil {
			return fmt.Errorf("\"nbf\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}

		if t.Nbf == nil {
			if err := jw.WriteNull(); err != nil {
				return fmt.Errorf("t.Nbf: %w", err)
			}
		} else {
			if err := jw.WriteInt64(int64(*t.Nbf)); err != nil {
				return fmt.Errorf("t.Nbf: %w", err)
			}
		}

		written++
	}
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Nonce ([]uint8) (slice)
	if len("nonce") > 8192 {
		return fmt.Errorf("String in field \"nonce\" was too long")
	}
	if err := jw.WriteString(string("nonce")); err != nil {
		return fmt.Errorf("\"nonce\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Nonce) > 2097152 {
		return fmt.Errorf("Byte array in field t.Nonce was too long")
	}

	if err := jw.WriteBytes(t.Nonce); err != nil {
		return fmt.Errorf("t.Nonce: %w", err)
	}

	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Pol (policy.Policy) (struct)
	if len("pol") > 8192 {
		return fmt.Errorf("String in field \"pol\" was too long")
	}
	if err := jw.WriteString(string("pol")); err != nil {
		return fmt.Errorf("\"pol\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Pol.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Pol: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Sub (did.DID) (struct)
	if len("sub") > 8192 {
		return fmt.Errorf("String in field \"sub\" was too long")
	}
	if err := jw.WriteString(string("sub")); err != nil {
		return fmt.Errorf("\"sub\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Sub.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Sub: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *TokenPayloadModel1_0_0_rc1) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = TokenPayloadModel1_0_0_rc1{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("TokenPayloadModel1_0_0_rc1: string too large")
				}
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
			}
			switch name {

			// t.Aud (did.DID) (struct)
			case "aud":

				if err := t.Aud.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Aud: %w", err)
				}

				// t.Cmd (command.Command) (string)
			case "cmd":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Cmd: string too long")
						}
						return fmt.Errorf("t.Cmd: %w", err)
					}
					t.Cmd = command.Command(sval)
				}

				// t.Exp (ucan.UTCUnixTimestamp) (int64)
			case "exp":
				{

					nval, err := jr.ReadNumberAsInt64OrNull()
					if err != nil {
						return fmt.Errorf("t.Exp: %w", err)
					}
					if nval != nil {
						typed := ucan.UTCUnixTimestamp(*nval)
						t.Exp = &typed
					}

				}

				// t.Iss (did.DID) (struct)
			case "iss":

				if err := t.Iss.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Iss: %w", err)
				}

				// t.Meta (datamodel.Raw) (struct)
			case "meta":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("t.Meta: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("t.Meta: %w", err)
						}
					} else {
						t.Meta = new(datamodel.Raw)
						if err := t.Meta.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.Meta pointer: %w", err)
						}
					}
				}

				// t.Nbf (ucan.UTCUnixTimestamp) (int64)
			case "nbf":
				{

					nval, err := jr.ReadNumberAsInt64OrNull()
					if err != nil {
						return fmt.Errorf("t.Nbf: %w", err)
					}
					if nval != nil {
						typed := ucan.UTCUnixTimestamp(*nval)
						t.Nbf = &typed
					}

				}

				// t.Nonce ([]uint8) (slice)
			case "nonce":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Nonce: byte array too large")
						}
						return fmt.Errorf("t.Nonce: %w", err)
					}
					if len(bval) > 0 {
						t.Nonce = []uint8(bval)
					}
				}

				// t.Pol (policy.Policy) (struct)
			case "pol":

				if err := t.Pol.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Pol: %w", err)
				}

				// t.Sub (did.DID) (struct)
			case "sub":

				if err := t.Sub.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Sub: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("TokenPayloadModel1_0_0_rc1: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("TokenPayloadModel1_0_0_rc1: map too large")
			}
		}
	}

	return nil
}
func (t *SigPayloadModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Header ([]uint8) (slice)
	if len("h") > 8192 {
		return fmt.Errorf("String in field \"h\" was too long")
	}
	if err := jw.WriteString(string("h")); err != nil {
		return fmt.Errorf("\"h\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Header) > 2097152 {
		return fmt.Errorf("Byte array in field t.Header was too long")
	}

	if err := jw.WriteBytes(t.Header); err != nil {
		return fmt.Errorf("t.Header: %w", err)
	}

	written++
	if t.TokenPayload1_0_0_rc1 != nil {
		if written > 0 {
			if err := jw.WriteComma(); err != nil {
				return err
			}
		}
	}

	// t.TokenPayload1_0_0_rc1 (datamodel.TokenPayloadModel1_0_0_rc1) (struct)
	if t.TokenPayload1_0_0_rc1 != nil {
		if len("ucan/dlg@1.0.0-rc.1") > 8192 {
			return fmt.Errorf("String in field \"ucan/dlg@1.0.0-rc.1\" was too long")
		}
		if err := jw.WriteString(string("ucan/dlg@1.0.0-rc.1")); err != nil {
			return fmt.Errorf("\"ucan/dlg@1.0.0-rc.1\": %w", err)
		}
		if err := jw.WriteObjectColon(); err != nil {
			return err
		}
		if err := t.TokenPayload1_0_0_rc1.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("t.TokenPayload1_0_0_rc1: %w", err)
		}
		written++
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *SigPayloadModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = SigPayloadModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("SigPayloadModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("SigPayloadModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("SigPayloadModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("SigPayloadModel: string too large")
				}
				return fmt.Errorf("SigPayloadModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("SigPayloadModel: %w", err)
			}
			switch name {

			// t.Header ([]uint8) (slice)
			case "h":

				{
					bval, err := jr.ReadBytes(2097152)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Header: byte array too large")
						}
						return fmt.Errorf("t.Header: %w", err)
					}
					if len(bval) > 0 {
						t.Header = []uint8(bval)
					}
				}

				// t.TokenPayload1_0_0_rc1 (datamodel.TokenPayloadModel1_0_0_rc1) (struct)
			case "ucan/dlg@1.0.0-rc.1":

				{
					null, err := jr.PeekNull()
					if err != nil {
						return fmt.Errorf("t.TokenPayload1_0_0_rc1: %w", err)
					}
					if null {
						if err := jr.ReadNull(); err != nil {
							return fmt.Errorf("t.TokenPayload1_0_0_rc1: %w", err)
						}
					} else {
						t.TokenPayload1_0_0_rc1 = new(TokenPayloadModel1_0_0_rc1)
						if err := t.TokenPayload1_0_0_rc1.UnmarshalDagJSON(jr); err != nil {
							return fmt.Errorf("unmarshaling t.TokenPayload1_0_0_rc1 pointer: %w", err)
						}
					}
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("SigPayloadModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("SigPayloadModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("SigPayloadModel: map too large")
			}
		}
	}

	return nil
}
