// Code generated by fieldgen; DO NOT EDIT.

package fields

import (
	policy "github.com/fil-forge/ucantone/ucan/delegation/policy"
)

// EmailsListArgumentsFields is the policy field descriptor type for EmailsListArguments.
type EmailsListArgumentsFields struct {
	Limit policy.Selector[uint64]
}

// MessageSendArgumentsFields is the policy field descriptor type for MessageSendArguments.
type MessageSendArgumentsFields struct {
	To      policy.SliceSelector[policy.Selector[string]]
	Subject policy.Selector[string]
	Message policy.Selector[string]
}

// EchoArgumentsFields is the policy field descriptor type for EchoArguments.
type EchoArgumentsFields struct {
	Message policy.Selector[string]
}

// EmailsListArguments is the policy field descriptor for EmailsListArguments.
var EmailsListArguments = EmailsListArgumentsFields{
	Limit: policy.NewSelector[uint64](".limit"),
}

// MessageSendArguments is the policy field descriptor for MessageSendArguments.
var MessageSendArguments = MessageSendArgumentsFields{
	To:      policy.NewSliceSelector[policy.Selector[string]](".to", policy.NewSelector[string](".")),
	Subject: policy.NewSelector[string](".subject"),
	Message: policy.NewSelector[string](".message"),
}

// EchoArguments is the policy field descriptor for EchoArguments.
var EchoArguments = EchoArgumentsFields{
	Message: policy.NewSelector[string](".message"),
}
