name: Go Checks

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-check:
    uses: ipdxco/unified-github-workflows/.github/workflows/go-check.yml@9f5f9a1d74ef7b0b2b843545aa8a2c675fe52eb1 # v1.0
